export { default as Hero } from "./Hero";
export { default as AboutUs } from "./AboutUs";
export { default as WorkExamples } from "./WorkExamples";
export { default as OurServices } from "./OurServices";
export { default as OurCustomers } from "./OurCustomers";
export { default as OurServicesList } from "./OurServices/OurServicesList";
export { default as OurServicesListItem } from "./OurServices/OurServicesListItem";
export { default as WorkExamplesItems } from "./WorkExamples/WorkExamplesItems";
export { default as WorkExamplesItem } from "./WorkExamples/WorkExamplesItem";
